version: "3.8"

services:
  postgres:
    image: postgres:latest
    container_name: postgres-student-registration
    environment:
      POSTGRES_DB: student_registration_system
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres-data:
    name: student-registration-postgres-data
